name: Update Node.js versions
author: Joram van den Boezem
description:
  Update you repository to the latest Node.js versions. Supports updating GitHub
  workflows and package.json engines.
inputs:
  versions:
    description: Node versions to select
    required: true
    default: |
      latest
      lts
      lts/-1
      lts/-2
  versions.filter-eol:
    description: Filter out Node versions which are end-of-life
    required: false
    default: true
  updaters.workflows:
    description: Update GitHub workflows
    required: false
    default: true
  updaters.workflows.variable:
    description: Update GitHub workflows
    required: false
    default: node-version
  updaters.engines:
    description: Update package.json `engines`
    required: false
    default: true
  updaters.files:
    description: Update arbitrary files
    required: false
    default: false
  updaters.files.glob:
    description: Glob pattern for files to update
    required: false
  updaters.files.regex:
    description: Matches will be replaced with the template
    required: false
  updaters.files.template:
    description: Replace matches with this template
    required: false
outputs:
  versions:
    description: The Node versions to update to as stringified JSON array
runs:
  using: node20
  main: dist/index.cjs
branding:
  icon: arrow-up
  color: green
