name: update-node-versions
author: Joram van den Boezem
description: Description of update-node-versions action
inputs:
  versions:
    description: Node versions to select
    required: true
    default: |
      lts
      lts/-1
      lts/-2
  versions.filter-eol:
    description: Filter out Node versions which are end-of-life
    required: false
    default: true
  updaters.workflows:
    description: Update GitHub workflows
    required: false
    default: true
  updaters.workflows.variable:
    description: Update GitHub workflows
    required: false
    default: node-version
  updaters.engines:
    description: Update package.json `engines`
    required: false
    default: true
outputs:
  versions:
    description: The Node versions to update to as stringified JSON array
runs:
  using: node16
  main: dist/index.cjs
branding:
  icon: arrow-up
  color: green
