name: build-and-tag

on:
  release:
    types: [published, edited]

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.release.tag_name }}
      - run: yarn install
      - run: yarn build
      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
